### ISSUE TITLE
URGENT GAMEBREAKING ISSUE

### ISSUE THREAD

**Issue by clsd0** [HumanoidSandvichDispenser/integradle#4]
u mad?  <img src="https://cdn.betterttv.net/emote/54fa8f1401e468494b85b537/3x.webp" width="28" height="28"/>

<img src="https://github.com/HumanoidSandvichDispenser/integradle/assets/139398877/ce261a2d-9fff-466f-b79b-31ca652a61d6" width="800"/>

**Comment by HumanoidSandvichDispenser** [comment]
140 iq bajs ![image](https://github.com/HumanoidSandvichDispenser/integradle/assets/25856867/8a84a52b-e68c-497a-aefd-4c441042559c)
